name: Cypress Tests

on:
  push:
    branches-ignore:
      - "renovate/**"

jobs:
  ui-chrome-tests:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.18.0-chrome107-ff106-edge
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      - run: npm install

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v4
        with:
          command-prefix: "percy exec -- npx"
          start: npm start
          wait-on: "http://localhost:8081"
          wait-on-timeout: 120
          browser: chrome
          spec: cypress/e2e/isolation/*
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
